import { Inter, Roboto } from "next/font/google";
import "./globals.css";
//web
import "./css/web/main.css";
//reponsive
import "./css/reponsive/main.css";
//components
import ResponsiveHeader from "./(components)/(main)/header-main";
import ReactQueryProvider from "./ReactQueryProvider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        <ResponsiveHeader />
        <ReactQueryProvider>
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
